#!/usr/bin/env python3
"""
AEGIS-X Professional Report Generator
Generates industry-standard vulnerability reports suitable for bug bounty platforms,
enterprise clients, and security assessments.
"""

import json
import logging
import asyncio
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass, asdict
from datetime import datetime, timedelta
from pathlib import Path
import base64
import hashlib
import markdown
from jinja2 import Template, Environment, FileSystemLoader
import pdfkit
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from io import BytesIO
import requests

@dataclass
class VulnerabilityFinding:
    """Represents a vulnerability finding for reporting"""
    id: str
    title: str
    severity: str
    cvss_score: float
    cvss_vector: str
    description: str
    impact: str
    affected_url: str
    affected_parameter: str
    payload: str
    proof_of_concept: str
    remediation: str
    references: List[str]
    evidence_files: List[str]
    discovery_date: str
    verification_status: str
    bug_bounty_program: Optional[str]
    reward_potential: Optional[str]
    technical_details: Dict[str, Any]
    business_impact: str
    risk_rating: str

@dataclass
class ReportMetadata:
    """Report metadata and configuration"""
    report_id: str
    report_type: str  # bug_bounty, penetration_test, security_assessment
    target_name: str
    target_scope: List[str]
    assessment_period: str
    generated_date: str
    generated_by: str
    client_name: Optional[str]
    engagement_type: str
    report_classification: str
    version: str

@dataclass
class ExecutiveSummary:
    """Executive summary for the report"""
    total_vulnerabilities: int
    critical_count: int
    high_count: int
    medium_count: int
    low_count: int
    info_count: int
    overall_risk_rating: str
    key_findings: List[str]
    recommendations: List[str]
    business_impact_summary: str
    remediation_timeline: str

class ProfessionalReportGenerator:
    """
    Professional report generator for vulnerability assessments.
    Generates reports in multiple formats suitable for different audiences.
    """
    
    def __init__(self, output_dir: str = "output"):
        self.logger = logging.getLogger("AEGIS-X.ProfessionalReportGenerator")
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        
        # Create subdirectories
        self.reports_dir = self.output_dir / "reports"
        self.charts_dir = self.output_dir / "charts"
        self.templates_dir = Path("templates")
        
        for dir_path in [self.reports_dir, self.charts_dir, self.templates_dir]:
            dir_path.mkdir(exist_ok=True)
        
        # Initialize Jinja2 environment
        self.jinja_env = Environment(
            loader=FileSystemLoader(str(self.templates_dir)),
            autoescape=True
        )
        
        # Report templates
        self._create_report_templates()
        
        # Styling configuration
        self.report_styles = {
            'colors': {
                'critical': '#DC2626',
                'high': '#EA580C',
                'medium': '#D97706',
                'low': '#65A30D',
                'info': '#0891B2',
                'primary': '#1F2937',
                'secondary': '#6B7280',
                'background': '#F9FAFB'
            },
            'fonts': {
                'title': 'Helvetica-Bold',
                'heading': 'Helvetica-Bold',
                'body': 'Helvetica',
                'code': 'Courier'
            }
        }
        
        self.logger.info("📊 Professional Report Generator initialized")
    
    def _create_report_templates(self):
        """Create report templates"""
        
        # Bug Bounty Report Template
        bug_bounty_template = """
# {{ metadata.target_name }} Security Assessment Report

**Report ID:** {{ metadata.report_id }}  
**Assessment Date:** {{ metadata.assessment_period }}  
**Generated:** {{ metadata.generated_date }}  
**Generated By:** {{ metadata.generated_by }}  

---

## Executive Summary

This security assessment identified **{{ executive_summary.total_vulnerabilities }}** vulnerabilities across the target scope. The findings include **{{ executive_summary.critical_count }}** Critical, **{{ executive_summary.high_count }}** High, **{{ executive_summary.medium_count }}** Medium, and **{{ executive_summary.low_count }}** Low severity issues.

**Overall Risk Rating:** {{ executive_summary.overall_risk_rating }}

### Key Findings
{% for finding in executive_summary.key_findings %}
- {{ finding }}
{% endfor %}

### Business Impact
{{ executive_summary.business_impact_summary }}

---

## Vulnerability Summary

| Severity | Count | Percentage |
|----------|-------|------------|
| Critical | {{ executive_summary.critical_count }} | {{ "%.1f"|format((executive_summary.critical_count / executive_summary.total_vulnerabilities * 100) if executive_summary.total_vulnerabilities > 0 else 0) }}% |
| High | {{ executive_summary.high_count }} | {{ "%.1f"|format((executive_summary.high_count / executive_summary.total_vulnerabilities * 100) if executive_summary.total_vulnerabilities > 0 else 0) }}% |
| Medium | {{ executive_summary.medium_count }} | {{ "%.1f"|format((executive_summary.medium_count / executive_summary.total_vulnerabilities * 100) if executive_summary.total_vulnerabilities > 0 else 0) }}% |
| Low | {{ executive_summary.low_count }} | {{ "%.1f"|format((executive_summary.low_count / executive_summary.total_vulnerabilities * 100) if executive_summary.total_vulnerabilities > 0 else 0) }}% |

---

## Detailed Findings

{% for finding in findings %}
### {{ loop.index }}. {{ finding.title }}

**Vulnerability ID:** {{ finding.id }}  
**Severity:** {{ finding.severity.upper() }}  
**CVSS Score:** {{ finding.cvss_score }}/10.0  
**CVSS Vector:** {{ finding.cvss_vector }}  

#### Description
{{ finding.description }}

#### Technical Details
- **Affected URL:** {{ finding.affected_url }}
- **Affected Parameter:** {{ finding.affected_parameter }}
- **Discovery Date:** {{ finding.discovery_date }}
- **Verification Status:** {{ finding.verification_status }}

#### Impact
{{ finding.impact }}

#### Business Impact
{{ finding.business_impact }}

#### Proof of Concept
```
{{ finding.proof_of_concept }}
```

#### Payload Used
```
{{ finding.payload }}
```

#### Remediation
{{ finding.remediation }}

#### References
{% for reference in finding.references %}
- {{ reference }}
{% endfor %}

---
{% endfor %}

## Recommendations

{% for recommendation in executive_summary.recommendations %}
{{ loop.index }}. {{ recommendation }}
{% endfor %}

## Remediation Timeline

{{ executive_summary.remediation_timeline }}

---

**Report Classification:** {{ metadata.report_classification }}  
**Version:** {{ metadata.version }}  

*This report was generated by AEGIS-X Professional Security Assessment Platform*
"""
        
        # Save template
        template_path = self.templates_dir / "bug_bounty_report.md"
        with open(template_path, 'w') as f:
            f.write(bug_bounty_template)
        
        # HackerOne Report Template
        hackerone_template = """
## Summary

{{ finding.title }}

## Description

{{ finding.description }}

## Steps To Reproduce

1. Navigate to {{ finding.affected_url }}
2. Inject the following payload into the {{ finding.affected_parameter }} parameter:
   ```
   {{ finding.payload }}
   ```
3. Observe the vulnerability manifestation

## Proof of Concept

{{ finding.proof_of_concept }}

## Impact

{{ finding.impact }}

{{ finding.business_impact }}

## Remediation

{{ finding.remediation }}

## Supporting Material/References

{% for reference in finding.references %}
- {{ reference }}
{% endfor %}

## System Information

- **Discovery Date:** {{ finding.discovery_date }}
- **CVSS Score:** {{ finding.cvss_score }}/10.0
- **CVSS Vector:** {{ finding.cvss_vector }}
- **Verification Status:** {{ finding.verification_status }}

---

*Discovered by AEGIS-X Professional Security Research*
"""
        
        # Save HackerOne template
        hackerone_path = self.templates_dir / "hackerone_report.md"
        with open(hackerone_path, 'w') as f:
            f.write(hackerone_template)
        
        # Bugcrowd Report Template
        bugcrowd_template = """
# {{ finding.title }}

## Vulnerability Details

**Severity:** {{ finding.severity.upper() }}  
**CVSS Score:** {{ finding.cvss_score }}/10.0  
**Affected Asset:** {{ finding.affected_url }}  
**Vulnerability Type:** {{ finding.technical_details.get('vulnerability_type', 'Unknown') }}  

## Description

{{ finding.description }}

## Reproduction Steps

1. Access the target URL: {{ finding.affected_url }}
2. Locate the vulnerable parameter: {{ finding.affected_parameter }}
3. Submit the following payload:
   ```
   {{ finding.payload }}
   ```
4. Observe the security vulnerability

## Proof of Concept

{{ finding.proof_of_concept }}

## Impact Assessment

{{ finding.impact }}

### Business Impact
{{ finding.business_impact }}

## Recommended Fix

{{ finding.remediation }}

## Additional Information

- **Discovery Method:** {{ finding.technical_details.get('discovery_method', 'Automated + Manual') }}
- **Verification Status:** {{ finding.verification_status }}
- **Risk Rating:** {{ finding.risk_rating }}

## References

{% for reference in finding.references %}
- {{ reference }}
{% endfor %}

---

*Report generated by AEGIS-X Professional Bug Bounty Platform*
"""
        
        # Save Bugcrowd template
        bugcrowd_path = self.templates_dir / "bugcrowd_report.md"
        with open(bugcrowd_path, 'w') as f:
            f.write(bugcrowd_template)
    
    async def generate_comprehensive_report(self, findings: List[VulnerabilityFinding], 
                                          metadata: ReportMetadata) -> Dict[str, str]:
        """
        Generate comprehensive security assessment report in multiple formats
        """
        self.logger.info(f"📊 Generating comprehensive report for {len(findings)} findings")
        
        try:
            # Generate executive summary
            executive_summary = self._generate_executive_summary(findings)
            
            # Generate charts and visualizations
            chart_paths = await self._generate_charts(findings, metadata)
            
            # Generate reports in different formats
            report_paths = {}
            
            # Markdown report
            markdown_path = await self._generate_markdown_report(
                findings, metadata, executive_summary
            )
            report_paths['markdown'] = str(markdown_path)
            
            # HTML report
            html_path = await self._generate_html_report(
                findings, metadata, executive_summary, chart_paths
            )
            report_paths['html'] = str(html_path)
            
            # PDF report
            pdf_path = await self._generate_pdf_report(
                findings, metadata, executive_summary, chart_paths
            )
            report_paths['pdf'] = str(pdf_path)
            
            # JSON report (for API consumption)
            json_path = await self._generate_json_report(
                findings, metadata, executive_summary
            )
            report_paths['json'] = str(json_path)
            
            # CSV report (for spreadsheet analysis)
            csv_path = await self._generate_csv_report(findings, metadata)
            report_paths['csv'] = str(csv_path)
            
            self.logger.info(f"✅ Comprehensive report generated successfully")
            return report_paths
            
        except Exception as e:
            self.logger.error(f"❌ Failed to generate comprehensive report: {e}")
            raise
    
    async def generate_bug_bounty_reports(self, findings: List[VulnerabilityFinding]) -> Dict[str, List[str]]:
        """
        Generate individual bug bounty reports for each platform
        """
        self.logger.info(f"🎯 Generating bug bounty reports for {len(findings)} findings")
        
        platform_reports = {
            'hackerone': [],
            'bugcrowd': [],
            'intigriti': [],
            'generic': []
        }
        
        try:
            for finding in findings:
                # Generate HackerOne format
                hackerone_report = await self._generate_hackerone_report(finding)
                platform_reports['hackerone'].append(hackerone_report)
                
                # Generate Bugcrowd format
                bugcrowd_report = await self._generate_bugcrowd_report(finding)
                platform_reports['bugcrowd'].append(bugcrowd_report)
                
                # Generate Intigriti format
                intigriti_report = await self._generate_intigriti_report(finding)
                platform_reports['intigriti'].append(intigriti_report)
                
                # Generate generic format
                generic_report = await self._generate_generic_bug_bounty_report(finding)
                platform_reports['generic'].append(generic_report)
            
            self.logger.info(f"✅ Bug bounty reports generated for all platforms")
            return platform_reports
            
        except Exception as e:
            self.logger.error(f"❌ Failed to generate bug bounty reports: {e}")
            raise
    
    def _generate_executive_summary(self, findings: List[VulnerabilityFinding]) -> ExecutiveSummary:
        """Generate executive summary from findings"""
        
        # Count vulnerabilities by severity
        severity_counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0, 'info': 0}
        
        for finding in findings:
            severity = finding.severity.lower()
            if severity in severity_counts:
                severity_counts[severity] += 1
        
        # Determine overall risk rating
        if severity_counts['critical'] > 0:
            overall_risk = "Critical"
        elif severity_counts['high'] > 0:
            overall_risk = "High"
        elif severity_counts['medium'] > 0:
            overall_risk = "Medium"
        elif severity_counts['low'] > 0:
            overall_risk = "Low"
        else:
            overall_risk = "Informational"
        
        # Generate key findings
        key_findings = []
        critical_findings = [f for f in findings if f.severity.lower() == 'critical']
        high_findings = [f for f in findings if f.severity.lower() == 'high']
        
        for finding in critical_findings[:3]:  # Top 3 critical
            key_findings.append(f"Critical: {finding.title}")
        
        for finding in high_findings[:2]:  # Top 2 high
            key_findings.append(f"High: {finding.title}")
        
        # Generate recommendations
        recommendations = [
            "Immediately address all Critical and High severity vulnerabilities",
            "Implement a comprehensive security testing program",
            "Conduct regular security assessments and penetration testing",
            "Establish a vulnerability management process",
            "Provide security training for development teams"
        ]
        
        # Business impact summary
        business_impact = self._generate_business_impact_summary(findings, severity_counts)
        
        # Remediation timeline
        remediation_timeline = self._generate_remediation_timeline(severity_counts)
        
        return ExecutiveSummary(
            total_vulnerabilities=len(findings),
            critical_count=severity_counts['critical'],
            high_count=severity_counts['high'],
            medium_count=severity_counts['medium'],
            low_count=severity_counts['low'],
            info_count=severity_counts['info'],
            overall_risk_rating=overall_risk,
            key_findings=key_findings,
            recommendations=recommendations,
            business_impact_summary=business_impact,
            remediation_timeline=remediation_timeline
        )
    
    def _generate_business_impact_summary(self, findings: List[VulnerabilityFinding], 
                                        severity_counts: Dict[str, int]) -> str:
        """Generate business impact summary"""
        
        impact_parts = []
        
        if severity_counts['critical'] > 0:
            impact_parts.append(
                f"The {severity_counts['critical']} Critical vulnerabilities pose immediate "
                "risk to business operations and could result in complete system compromise, "
                "data breaches, and significant financial losses."
            )
        
        if severity_counts['high'] > 0:
            impact_parts.append(
                f"The {severity_counts['high']} High severity vulnerabilities could lead to "
                "unauthorized access to sensitive data, system manipulation, and potential "
                "regulatory compliance violations."
            )
        
        if severity_counts['medium'] > 0:
            impact_parts.append(
                f"The {severity_counts['medium']} Medium severity vulnerabilities may allow "
                "limited unauthorized access and could be chained with other vulnerabilities "
                "to increase impact."
            )
        
        # Calculate potential financial impact
        financial_impact = self._calculate_financial_impact(severity_counts)
        impact_parts.append(f"Estimated potential financial impact: {financial_impact}")
        
        return " ".join(impact_parts)
    
    def _calculate_financial_impact(self, severity_counts: Dict[str, int]) -> str:
        """Calculate estimated financial impact"""
        
        # Conservative estimates based on industry data
        impact_estimates = {
            'critical': 500000,  # $500K per critical vulnerability
            'high': 100000,     # $100K per high vulnerability
            'medium': 25000,    # $25K per medium vulnerability
            'low': 5000         # $5K per low vulnerability
        }
        
        total_impact = 0
        for severity, count in severity_counts.items():
            if severity in impact_estimates:
                total_impact += count * impact_estimates[severity]
        
        if total_impact >= 1000000:
            return f"${total_impact/1000000:.1f}M+"
        elif total_impact >= 1000:
            return f"${total_impact/1000:.0f}K+"
        else:
            return f"${total_impact:,.0f}+"
    
    def _generate_remediation_timeline(self, severity_counts: Dict[str, int]) -> str:
        """Generate remediation timeline recommendations"""
        
        timeline_parts = []
        
        if severity_counts['critical'] > 0:
            timeline_parts.append("Critical vulnerabilities: Fix within 24 hours")
        
        if severity_counts['high'] > 0:
            timeline_parts.append("High severity vulnerabilities: Fix within 72 hours")
        
        if severity_counts['medium'] > 0:
            timeline_parts.append("Medium severity vulnerabilities: Fix within 1 week")
        
        if severity_counts['low'] > 0:
            timeline_parts.append("Low severity vulnerabilities: Fix within 1 month")
        
        return "; ".join(timeline_parts)
    
    async def _generate_charts(self, findings: List[VulnerabilityFinding], 
                             metadata: ReportMetadata) -> Dict[str, str]:
        """Generate charts and visualizations"""
        
        chart_paths = {}
        
        try:
            # Severity distribution pie chart
            severity_chart = await self._create_severity_distribution_chart(findings)
            chart_paths['severity_distribution'] = severity_chart
            
            # CVSS score distribution histogram
            cvss_chart = await self._create_cvss_distribution_chart(findings)
            chart_paths['cvss_distribution'] = cvss_chart
            
            # Vulnerability types bar chart
            types_chart = await self._create_vulnerability_types_chart(findings)
            chart_paths['vulnerability_types'] = types_chart
            
            # Risk timeline chart
            timeline_chart = await self._create_risk_timeline_chart(findings)
            chart_paths['risk_timeline'] = timeline_chart
            
        except Exception as e:
            self.logger.warning(f"Failed to generate some charts: {e}")
        
        return chart_paths
    
    async def _create_severity_distribution_chart(self, findings: List[VulnerabilityFinding]) -> str:
        """Create severity distribution pie chart"""
        
        # Count severities
        severity_counts = {}
        for finding in findings:
            severity = finding.severity.capitalize()
            severity_counts[severity] = severity_counts.get(severity, 0) + 1
        
        # Create pie chart
        plt.figure(figsize=(10, 8))
        colors = [self.report_styles['colors'][sev.lower()] for sev in severity_counts.keys()]
        
        wedges, texts, autotexts = plt.pie(
            severity_counts.values(),
            labels=severity_counts.keys(),
            colors=colors,
            autopct='%1.1f%%',
            startangle=90
        )
        
        plt.title('Vulnerability Severity Distribution', fontsize=16, fontweight='bold')
        
        # Save chart
        chart_path = self.charts_dir / f"severity_distribution_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        plt.savefig(chart_path, dpi=300, bbox_inches='tight')
        plt.close()
        
        return str(chart_path)
    
    async def _create_cvss_distribution_chart(self, findings: List[VulnerabilityFinding]) -> str:
        """Create CVSS score distribution histogram"""
        
        cvss_scores = [finding.cvss_score for finding in findings if finding.cvss_score > 0]
        
        if not cvss_scores:
            return ""
        
        plt.figure(figsize=(12, 6))
        plt.hist(cvss_scores, bins=20, color=self.report_styles['colors']['primary'], alpha=0.7)
        plt.xlabel('CVSS Score')
        plt.ylabel('Number of Vulnerabilities')
        plt.title('CVSS Score Distribution', fontsize=16, fontweight='bold')
        plt.grid(True, alpha=0.3)
        
        # Add severity ranges
        plt.axvspan(0, 3.9, alpha=0.2, color=self.report_styles['colors']['low'], label='Low')
        plt.axvspan(4.0, 6.9, alpha=0.2, color=self.report_styles['colors']['medium'], label='Medium')
        plt.axvspan(7.0, 8.9, alpha=0.2, color=self.report_styles['colors']['high'], label='High')
        plt.axvspan(9.0, 10.0, alpha=0.2, color=self.report_styles['colors']['critical'], label='Critical')
        
        plt.legend()
        
        # Save chart
        chart_path = self.charts_dir / f"cvss_distribution_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        plt.savefig(chart_path, dpi=300, bbox_inches='tight')
        plt.close()
        
        return str(chart_path)
    
    async def _create_vulnerability_types_chart(self, findings: List[VulnerabilityFinding]) -> str:
        """Create vulnerability types bar chart"""
        
        # Extract vulnerability types
        vuln_types = {}
        for finding in findings:
            vuln_type = finding.technical_details.get('vulnerability_type', 'Unknown')
            vuln_types[vuln_type] = vuln_types.get(vuln_type, 0) + 1
        
        if not vuln_types:
            return ""
        
        plt.figure(figsize=(12, 8))
        bars = plt.bar(vuln_types.keys(), vuln_types.values(), 
                      color=self.report_styles['colors']['primary'])
        
        plt.xlabel('Vulnerability Type')
        plt.ylabel('Count')
        plt.title('Vulnerability Types Distribution', fontsize=16, fontweight='bold')
        plt.xticks(rotation=45, ha='right')
        
        # Add value labels on bars
        for bar in bars:
            height = bar.get_height()
            plt.text(bar.get_x() + bar.get_width()/2., height,
                    f'{int(height)}', ha='center', va='bottom')
        
        # Save chart
        chart_path = self.charts_dir / f"vulnerability_types_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        plt.savefig(chart_path, dpi=300, bbox_inches='tight')
        plt.close()
        
        return str(chart_path)
    
    async def _create_risk_timeline_chart(self, findings: List[VulnerabilityFinding]) -> str:
        """Create risk timeline chart"""
        
        # Group findings by discovery date
        date_counts = {}
        for finding in findings:
            date = finding.discovery_date.split('T')[0]  # Extract date part
            date_counts[date] = date_counts.get(date, 0) + 1
        
        if len(date_counts) < 2:
            return ""
        
        # Sort dates
        sorted_dates = sorted(date_counts.keys())
        counts = [date_counts[date] for date in sorted_dates]
        
        plt.figure(figsize=(12, 6))
        plt.plot(sorted_dates, counts, marker='o', linewidth=2, markersize=6,
                color=self.report_styles['colors']['primary'])
        
        plt.xlabel('Discovery Date')
        plt.ylabel('Vulnerabilities Found')
        plt.title('Vulnerability Discovery Timeline', fontsize=16, fontweight='bold')
        plt.xticks(rotation=45)
        plt.grid(True, alpha=0.3)
        
        # Save chart
        chart_path = self.charts_dir / f"risk_timeline_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        plt.savefig(chart_path, dpi=300, bbox_inches='tight')
        plt.close()
        
        return str(chart_path)
    
    async def _generate_markdown_report(self, findings: List[VulnerabilityFinding],
                                      metadata: ReportMetadata,
                                      executive_summary: ExecutiveSummary) -> Path:
        """Generate markdown report"""
        
        template = self.jinja_env.get_template('bug_bounty_report.md')
        
        report_content = template.render(
            findings=findings,
            metadata=metadata,
            executive_summary=executive_summary
        )
        
        # Save report
        report_path = self.reports_dir / f"{metadata.report_id}_report.md"
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        return report_path
    
    async def _generate_html_report(self, findings: List[VulnerabilityFinding],
                                  metadata: ReportMetadata,
                                  executive_summary: ExecutiveSummary,
                                  chart_paths: Dict[str, str]) -> Path:
        """Generate HTML report"""
        
        # Convert markdown to HTML
        markdown_path = await self._generate_markdown_report(findings, metadata, executive_summary)
        
        with open(markdown_path, 'r', encoding='utf-8') as f:
            markdown_content = f.read()
        
        html_content = markdown.markdown(markdown_content, extensions=['tables', 'codehilite'])
        
        # Create full HTML document
        html_template = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{metadata.target_name} Security Assessment Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9fafb;
        }}
        .container {{
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1, h2, h3 {{ color: #1f2937; }}
        h1 {{ border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }}
        h2 {{ border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }}
        .severity-critical {{ color: #dc2626; font-weight: bold; }}
        .severity-high {{ color: #ea580c; font-weight: bold; }}
        .severity-medium {{ color: #d97706; font-weight: bold; }}
        .severity-low {{ color: #65a30d; font-weight: bold; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ border: 1px solid #e5e7eb; padding: 12px; text-align: left; }}
        th {{ background-color: #f3f4f6; font-weight: bold; }}
        pre {{ background: #f3f4f6; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        code {{ background: #f3f4f6; padding: 2px 4px; border-radius: 3px; }}
        .chart {{ text-align: center; margin: 20px 0; }}
        .chart img {{ max-width: 100%; height: auto; }}
    </style>
</head>
<body>
    <div class="container">
        {html_content}
        
        <h2>Visualizations</h2>
        <div class="charts">
            {self._generate_chart_html(chart_paths)}
        </div>
        
        <hr>
        <p><em>Report generated by AEGIS-X Professional Security Assessment Platform on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>
    </div>
</body>
</html>
"""
        
        # Save HTML report
        html_path = self.reports_dir / f"{metadata.report_id}_report.html"
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_template)
        
        return html_path
    
    def _generate_chart_html(self, chart_paths: Dict[str, str]) -> str:
        """Generate HTML for charts"""
        
        chart_html = ""
        for chart_name, chart_path in chart_paths.items():
            if chart_path and Path(chart_path).exists():
                # Convert to base64 for embedding
                with open(chart_path, 'rb') as f:
                    chart_data = base64.b64encode(f.read()).decode()
                
                chart_html += f"""
                <div class="chart">
                    <h3>{chart_name.replace('_', ' ').title()}</h3>
                    <img src="data:image/png;base64,{chart_data}" alt="{chart_name}">
                </div>
                """
        
        return chart_html
    
    async def _generate_pdf_report(self, findings: List[VulnerabilityFinding],
                                 metadata: ReportMetadata,
                                 executive_summary: ExecutiveSummary,
                                 chart_paths: Dict[str, str]) -> Path:
        """Generate PDF report"""
        
        # Generate HTML first
        html_path = await self._generate_html_report(findings, metadata, executive_summary, chart_paths)
        
        # Convert HTML to PDF
        pdf_path = self.reports_dir / f"{metadata.report_id}_report.pdf"
        
        try:
            # Configure PDF options
            options = {
                'page-size': 'A4',
                'margin-top': '0.75in',
                'margin-right': '0.75in',
                'margin-bottom': '0.75in',
                'margin-left': '0.75in',
                'encoding': "UTF-8",
                'no-outline': None,
                'enable-local-file-access': None
            }
            
            pdfkit.from_file(str(html_path), str(pdf_path), options=options)
            
        except Exception as e:
            self.logger.warning(f"Failed to generate PDF using pdfkit: {e}")
            # Fallback to ReportLab
            await self._generate_pdf_with_reportlab(findings, metadata, executive_summary, pdf_path)
        
        return pdf_path
    
    async def _generate_pdf_with_reportlab(self, findings: List[VulnerabilityFinding],
                                         metadata: ReportMetadata,
                                         executive_summary: ExecutiveSummary,
                                         pdf_path: Path):
        """Generate PDF using ReportLab as fallback"""
        
        doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
        styles = getSampleStyleSheet()
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER
        )
        story.append(Paragraph(f"{metadata.target_name} Security Assessment Report", title_style))
        story.append(Spacer(1, 20))
        
        # Metadata
        story.append(Paragraph(f"<b>Report ID:</b> {metadata.report_id}", styles['Normal']))
        story.append(Paragraph(f"<b>Assessment Period:</b> {metadata.assessment_period}", styles['Normal']))
        story.append(Paragraph(f"<b>Generated:</b> {metadata.generated_date}", styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Executive Summary
        story.append(Paragraph("Executive Summary", styles['Heading2']))
        story.append(Paragraph(executive_summary.business_impact_summary, styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Vulnerability Summary Table
        story.append(Paragraph("Vulnerability Summary", styles['Heading2']))
        
        table_data = [
            ['Severity', 'Count', 'Percentage'],
            ['Critical', str(executive_summary.critical_count), f"{(executive_summary.critical_count / executive_summary.total_vulnerabilities * 100) if executive_summary.total_vulnerabilities > 0 else 0:.1f}%"],
            ['High', str(executive_summary.high_count), f"{(executive_summary.high_count / executive_summary.total_vulnerabilities * 100) if executive_summary.total_vulnerabilities > 0 else 0:.1f}%"],
            ['Medium', str(executive_summary.medium_count), f"{(executive_summary.medium_count / executive_summary.total_vulnerabilities * 100) if executive_summary.total_vulnerabilities > 0 else 0:.1f}%"],
            ['Low', str(executive_summary.low_count), f"{(executive_summary.low_count / executive_summary.total_vulnerabilities * 100) if executive_summary.total_vulnerabilities > 0 else 0:.1f}%"]
        ]
        
        table = Table(table_data)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 14),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(table)
        story.append(PageBreak())
        
        # Detailed Findings
        story.append(Paragraph("Detailed Findings", styles['Heading2']))
        
        for i, finding in enumerate(findings, 1):
            story.append(Paragraph(f"{i}. {finding.title}", styles['Heading3']))
            story.append(Paragraph(f"<b>Severity:</b> {finding.severity.upper()}", styles['Normal']))
            story.append(Paragraph(f"<b>CVSS Score:</b> {finding.cvss_score}/10.0", styles['Normal']))
            story.append(Paragraph(f"<b>Description:</b> {finding.description}", styles['Normal']))
            story.append(Paragraph(f"<b>Impact:</b> {finding.impact}", styles['Normal']))
            story.append(Paragraph(f"<b>Remediation:</b> {finding.remediation}", styles['Normal']))
            story.append(Spacer(1, 20))
        
        # Build PDF
        doc.build(story)
    
    async def _generate_json_report(self, findings: List[VulnerabilityFinding],
                                  metadata: ReportMetadata,
                                  executive_summary: ExecutiveSummary) -> Path:
        """Generate JSON report"""
        
        report_data = {
            'metadata': asdict(metadata),
            'executive_summary': asdict(executive_summary),
            'findings': [asdict(finding) for finding in findings],
            'generated_at': datetime.now().isoformat(),
            'report_version': '1.0'
        }
        
        json_path = self.reports_dir / f"{metadata.report_id}_report.json"
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(report_data, f, indent=2, ensure_ascii=False)
        
        return json_path
    
    async def _generate_csv_report(self, findings: List[VulnerabilityFinding],
                                 metadata: ReportMetadata) -> Path:
        """Generate CSV report"""
        
        import csv
        
        csv_path = self.reports_dir / f"{metadata.report_id}_findings.csv"
        
        with open(csv_path, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            
            # Header
            writer.writerow([
                'ID', 'Title', 'Severity', 'CVSS Score', 'CVSS Vector',
                'Affected URL', 'Affected Parameter', 'Description',
                'Impact', 'Remediation', 'Discovery Date', 'Verification Status'
            ])
            
            # Data
            for finding in findings:
                writer.writerow([
                    finding.id,
                    finding.title,
                    finding.severity,
                    finding.cvss_score,
                    finding.cvss_vector,
                    finding.affected_url,
                    finding.affected_parameter,
                    finding.description,
                    finding.impact,
                    finding.remediation,
                    finding.discovery_date,
                    finding.verification_status
                ])
        
        return csv_path
    
    async def _generate_hackerone_report(self, finding: VulnerabilityFinding) -> str:
        """Generate HackerOne format report"""
        
        template = self.jinja_env.get_template('hackerone_report.md')
        report_content = template.render(finding=finding)
        
        # Save individual report
        report_path = self.reports_dir / f"hackerone_{finding.id}.md"
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        return str(report_path)
    
    async def _generate_bugcrowd_report(self, finding: VulnerabilityFinding) -> str:
        """Generate Bugcrowd format report"""
        
        template = self.jinja_env.get_template('bugcrowd_report.md')
        report_content = template.render(finding=finding)
        
        # Save individual report
        report_path = self.reports_dir / f"bugcrowd_{finding.id}.md"
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        return str(report_path)
    
    async def _generate_intigriti_report(self, finding: VulnerabilityFinding) -> str:
        """Generate Intigriti format report"""
        
        # Intigriti uses similar format to Bugcrowd
        return await self._generate_bugcrowd_report(finding)
    
    async def _generate_generic_bug_bounty_report(self, finding: VulnerabilityFinding) -> str:
        """Generate generic bug bounty report"""
        
        report_content = f"""# {finding.title}

## Vulnerability Summary

**Severity:** {finding.severity.upper()}  
**CVSS Score:** {finding.cvss_score}/10.0  
**CVSS Vector:** {finding.cvss_vector}  
**Affected Asset:** {finding.affected_url}  
**Affected Parameter:** {finding.affected_parameter}  

## Description

{finding.description}

## Steps to Reproduce

1. Navigate to the affected URL: {finding.affected_url}
2. Locate the vulnerable parameter: {finding.affected_parameter}
3. Submit the following payload:
   ```
   {finding.payload}
   ```
4. Observe the vulnerability manifestation

## Proof of Concept

{finding.proof_of_concept}

## Impact

{finding.impact}

### Business Impact
{finding.business_impact}

## Remediation

{finding.remediation}

## References

{chr(10).join(f'- {ref}' for ref in finding.references)}

## Additional Information

- **Discovery Date:** {finding.discovery_date}
- **Verification Status:** {finding.verification_status}
- **Risk Rating:** {finding.risk_rating}

---

*Report generated by AEGIS-X Professional Security Research Platform*
"""
        
        # Save individual report
        report_path = self.reports_dir / f"generic_{finding.id}.md"
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        return str(report_path)

# Example usage
if __name__ == "__main__":
    import asyncio
    
    # Example finding for testing
    test_finding = VulnerabilityFinding(
        id="AEGIS-001",
        title="Cross-Site Scripting (XSS) in Search Parameter",
        severity="high",
        cvss_score=7.5,
        cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        description="A reflected XSS vulnerability exists in the search parameter",
        impact="Attackers can execute malicious JavaScript in victim browsers",
        affected_url="https://example.com/search.php",
        affected_parameter="q",
        payload="<script>alert('XSS')</script>",
        proof_of_concept="Navigate to https://example.com/search.php?q=<script>alert('XSS')</script>",
        remediation="Implement proper input validation and output encoding",
        references=["https://owasp.org/www-project-top-ten/"],
        evidence_files=["screenshot1.png", "poc_video.mp4"],
        discovery_date=datetime.now().isoformat(),
        verification_status="Verified",
        bug_bounty_program="Example Bug Bounty",
        reward_potential="$500-$2000",
        technical_details={"vulnerability_type": "xss", "discovery_method": "automated"},
        business_impact="User account compromise and data theft",
        risk_rating="High"
    )
    
    test_metadata = ReportMetadata(
        report_id="AEGIS-REPORT-001",
        report_type="bug_bounty",
        target_name="Example Application",
        target_scope=["example.com", "*.example.com"],
        assessment_period="2024-01-01 to 2024-01-07",
        generated_date=datetime.now().isoformat(),
        generated_by="AEGIS-X Professional",
        client_name="Example Corp",
        engagement_type="Bug Bounty Assessment",
        report_classification="Confidential",
        version="1.0"
    )
    
    async def test_report_generation():
        generator = ProfessionalReportGenerator()
        
        # Generate comprehensive report
        report_paths = await generator.generate_comprehensive_report([test_finding], test_metadata)
        print("Generated comprehensive reports:")
        for format_type, path in report_paths.items():
            print(f"- {format_type.upper()}: {path}")
        
        # Generate bug bounty reports
        bug_bounty_reports = await generator.generate_bug_bounty_reports([test_finding])
        print("\nGenerated bug bounty reports:")
        for platform, reports in bug_bounty_reports.items():
            print(f"- {platform.upper()}: {len(reports)} reports")
    
    # Run test
    # asyncio.run(test_report_generation())